<a href="https://colab.research.google.com/github/omsai1682/Python-Lab/blob/main/lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY and PANDAS

In [4]:
import numpy as np
import pandas as pd


Create a Numpy Array

In [2]:
arr =np.array([10,20,30,40,50])
print('Original Array:',arr)

Original Array: [10 20 30 40 50]


Manipulate the Numpy Array

In [5]:
print(arr+5)
print(arr*2)
print(arr[arr>25])

[15 25 35 45 55]
[ 20  40  60  80 100]
[30 40 50]


Create a Pandas Dataframe

In [6]:
# Create a dictationary for the data
data ={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'score':[85.5,92.0,88.0,76.5]
}

# Create Dataframe
df = pd.DataFrame(data)
print("\nOriginal Dataframe:\n",df)




Original Dataframe:
       Name  Age  score
0    Alice   25   85.5
1      Bob   30   92.0
2  Charlie   35   88.0
3    David   40   76.5


Manipulate the Dataframe

In [7]:
# Add a new column 'passed' based on score
df['passed']=df['score']>=80
print("\nDataframe after adding 'passed' column:\n",df)

#Filter rows where Age>30
older_student=df[df['Age']>30]
print("\nstudents older than 30:\n",older_student)

# Calculate average score
average_score=df['score'].mean()
print("\nAverage Score:",average_score)


Dataframe after adding 'passed' column:
       Name  Age  score  passed
0    Alice   25   85.5    True
1      Bob   30   92.0    True
2  Charlie   35   88.0    True
3    David   40   76.5   False

students older than 30:
       Name  Age  score  passed
2  Charlie   35   88.0    True
3    David   40   76.5   False

Average Score: 85.5
